; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./boards

[env:esp32]
monitor_speed = 115200
platform = espressif32@6.13.0
board = lilygo-t-display-s3
framework = arduino
lib_ignore =
    display
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/DCRalph/dcr_display.git
    https://github.com/DCRalph/wireless_mesh.git
    https://github.com/dcralph/dcr_fatalHandler.git
    https://github.com/DCRalph/dcr_httpClient.git
    https://github.com/DCRalph/dcr_netLink.git
    https://github.com/DCRalph/dcr_logger.git
    https://github.com/DCRalph/dcr_files.git
    https://github.com/DCRalph/dcr_taskManager.git

build_unflags = 
	-std=gnu++11

build_type = debug
monitor_filters =
	time
	esp32_exception_decoder

build_flags = 
    -std=gnu++2a
    -D DISABLE_ALL_LIBRARY_WARNINGS
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
	; -D CORE_DEBUG_LEVEL=3
    -I $PROJECT_DIR/src
